# Example configuration for Agentic Redpanda

message_broker:
  bootstrap_servers:
    - "localhost:9092"
  security_protocol: "PLAINTEXT"
  auto_offset_reset: "latest"
  enable_auto_commit: true

agents:
  - agent_id: "assistant-1"
    agent_name: "AI Assistant"
    role: "general"
    llm_provider:
      provider_type: "openai"
      model: "gpt-3.5-turbo"
      api_key: "your-openai-api-key-here"
      max_tokens: 1000
      temperature: 0.7
      top_p: 1.0
    topics:
      - "general"
      - "random"
      - "help"
  
  - agent_id: "coder-1"
    agent_name: "Code Assistant"
    role: "programming"
    llm_provider:
      provider_type: "openai"
      model: "gpt-4"
      api_key: "your-openai-api-key-here"
      max_tokens: 2000
      temperature: 0.3
    topics:
      - "programming"
      - "code-review"
      - "general"
  
  - agent_id: "local-1"
    agent_name: "Local Assistant"
    role: "general"
    llm_provider:
      provider_type: "ollama"
      model: "llama2"
      base_url: "http://localhost:11434"
      max_tokens: 1000
      temperature: 0.7
    topics:
      - "local"
      - "general"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    - console
    - file

monitoring:
  enable_metrics: true
  metrics_port: 8080
  health_check_interval: 30
